export const PREMIUM_LIMITS = {
  FREE: {
    LIKES: 5,
    FAVORITES: 5,
    COLLECTIONS: 3,
  },
  PREMIUM: {
    LIKES: Infinity,
    FAVORITES: Infinity,
    COLLECTIONS: Infinity,
  },
} as const;

export const PREMIUM_FEATURES = {
  UNLIMITED_LIKES: 'UNLIMITED_LIKES',
  UNLIMITED_FAVORITES: 'UNLIMITED_FAVORITES',
  UNLIMITED_COLLECTIONS: 'UNLIMITED_COLLECTIONS',
  CUSTOM_THEMES: 'CUSTOM_THEMES',
  NOTIFICATIONS: 'NOTIFICATIONS',
  EXCLUSIVE_BADGES: 'EXCLUSIVE_BADGES',
} as const; 